### ISSUE TITLE
Неправильный вынос предиката "="

### ISSUE THREAD

**Issue by ylyxa** [bmstu-iu9/SMT-to-REF#10]
При выносе "=" константы выносятся как строковые переменные.
Например, для предложения 
`(assert (= "x" "B"))` 
на выходе получится
`('p0', (('str', 'x'), ('str', 'B')), '=', ('str', 'x'), ('str', 'B'))`
что не есть верный ответ, как я понял.

**Comment by ylyxa** [comment]
Еще бы проверить вынос других предикатов, я кроме "=" только contains проверил, он работает правильно.

**Comment by ylyxa** [comment]
В общем, проверил.
@StepanBog ты, похоже, просто не учел правило `[строка] ::= [константа]`, т.е. везде, где может стоять строковая переменная, может стоять и константа.

**Comment by ylyxa** [comment]
Это, оказывается, все мои косяки были, еще с парсера. Сейчас буду думать, как это все исправлять.

**Comment by ylyxa** [comment]
Исправил. В коммите с кодгеном уже все будет нормально.

**Comment by Mazdaywik** [comment]
Добавили к описанию коммита #10? Если нет, то `git commit --amend` Вам в помощь.
