### ISSUE TITLE
Построение КНФ на базе SMT-модели

### ISSUE THREAD

**Issue by TonitaN** [bmstu-iu9/SMT-to-REF#4]
Самое первое, что нужно будет сделать для обработки модели — это приведение логических выражений, стоящих внутри `assert`-предложений, в КНФ (конъюнктивную нормальную форму). Каждое такое логическое выражение --- это композиция логических операторов над предикатами --- равенствами либо утверждениями вида `(str.contains ...)`. Каждый такой предикат можно представить как функцию `P(x1,…,xn)` --- где `xi` --- это все параметры, используемые в двух частях равенства или в первом аргументе функции `(str.contains ...)`. Чтобы начать преобразование в КНФ, можно представить предикаты в такой форме, и дальше обращаться с функциями `P(x1,…,xn)` как с примитивами. За супер-эффективностью мы не гонимся, т.к. пишем прототип, поэтому можно применять любой алгоритм преобразования формулы к КНФ, например, через дистрибутивность и де Моргана.
 
Пример: дано
```
(declare-fun A() String)
(declare-fun B() String)
(declare-fun C() String)
(assert (not (and (str.contains B ‘’b’’) (and (str.contains C ‘’aa’’) (= A C)) (= A (str.++ B ‘’aa’’)))))
```
Приводим к предикатной форме:
```
(str.contains B ‘’b’’) → P1(B)
(str.contains C ‘’aa’’) → P2(C)
(= A C) → P3(A,C)
(= A (str.++ B ‘’aa’’)) → P4(A,B)
```
После объявления этих предикатов как логических примитивов получается вполне удобоваримая формула:
```
(not (and P1 (and P2 P3) P4))
```
Которую приводим в КНФ уже стандартно.

@StepanBog, алгоритм преобразования предикатной формы к КНФ уже можно делать. @ylyxa, токены у вас описаны интуитивно понятно, но всё-таки лучше, если при передаче задачи @StepanBog вы сделаете в коде краткие комментарии по интерфейсу взаимодействия с лексером.

**Comment by TonitaN** [comment]
Грубое приведение к КНФ состоит из трёх этапов.
1.  Протаскивание отрицания внутрь формулы с помощью законов де Моргана. Применяется, начиная с самой внешней формулы (сверху вниз по синтаксическому дереву).
2. Снятие парных отрицаний.
3. Использование закона дистрибутивности: `A v (B & C) <=> (A v B) & (A v C)`. Применяем также сверху вниз. 
Как только самый первый грубый вариант приведения к КНФ будет сделан, я закрою эту заявку и будут открыты заявки по оптимизациям КНФ и по переводу КНФ в рефал, которые уже могут быть обработаны независимо друг от друга.

**Comment by StepanBog** [comment]
Первые 2 шага сделаны 
Дистрибутивность пока не готова 
К 26му числу будет готова

**Comment by StepanBog** [comment]
Дистрибутивность подключена
Приведение к КНФ есть

**Comment by Mazdaywik** [comment]
Если бы в названия коммитов Вы добавляли `(#5)`, то они бы показывались здесь. И было бы понятно, что Вы сделали.
