### ISSUE TITLE
Чтение пути к файлу из командной строки

### ISSUE THREAD

**Issue by TonitaN** [bmstu-iu9/SMT-to-REF#5]
Чтобы сейчас посмотреть, как работает проект, приходится руками менять содержимое файлов `Parser.py` и `Lexer.py`. Нужно сделать запуск всего проекта с переменным именем файла.

**Comment by ylyxa** [comment]
Сделал базовый GUI для выбора входного и выходного файлов. В выходной пока ничего не пишется, ибо пока писать нечего.
