### ISSUE TITLE
Кодогенерация по КНФ

### ISSUE THREAD

**Issue by TonitaN** [bmstu-iu9/SMT-to-REF#8]
# Базовая кодогенерация

Дано: КНФ вида `(AND Dj_1 ... Dj_n)`, где `Dj_i = (OR L_(i,1) ... L_(i, k_i))` и *m* строковых переменных, которым соответствуют имена `e.Name_1`, ..., `e.Name_m` (см. заявку #7 ). Функция `convert` для литералов описана в заявке #7 .

Определяем стандартные функции `AND` и `OR`:
```
AND {
    e.x1 False e.x2 = False;
    e.Z = True;
}
OR {
    e.x1 True e.x2 = True;
    e.Z = False;
}
```
Пусть `convert(L_(i,j)) = CALL_(i,j)`
Порождаем входную точку:
```
$ENTRY Go {
    (e.Name_1) (e.Name_2) ... (e.Name_m)
        = <AND 
            <OR CALL_(1,1) ... CALL_(1,k_1)> 
             ... 
            <OR CALL_(n,1) ... CALL_(n,k_n)>
        >;
}
```

# Расшаривание общего аргумента

Допустим, в дизъюнкте имеются *M* литералов вида `(str.contains S [Const_i])`, *M>1*. Поскольку аргумент у них общий, расшарим его в рамках одной функции. Для этого сначала определим все такие пары *<[Const_i], [Const_j]>*, что *[Const_i]* является подстрокой *[Const_j]*, и выбросим члены дизъюнкции вида `(str.contains S [Const_j])`. Это работает, поскольку `(str.contains S [Const_j]) => (str.contains S [Const_i])`, а значит, `(str.contains S [Const_j]) v (str.contains S [Const_i]) <=> (str.contains S [Const_i])`, а жизнь при кодогенерации упростит. Если после этого остался только один литерал вышеуказанного вида, то дальнейшую оптимизацию применять уже не надо, иначе считаем, что осталось *m>1* литералов `(str.contains S [Const'_i])`.

Теперь вместо порождения *m*  вызовов функций порождаем только одну, с *m+1* предложением:
```
Infix_Multi_[Number] {
    e.1 [Const'_1] e.2 = True;
    e.1 [Const'_2] e.2 = True;
   ...
   e.Z = False;
}
```
Её вызываем внутри `Go` как обычно: `<Infix_Multi_[Number] S>`.

Если в дизъюнкте имеются *M* литералов вида `(not (str.contains S [Const_i]))`, *M>1*, то их тоже можно попытаться упростить по отношению подстроки. Для этого опять сначала определим все такие пары *<[Const_i], [Const_j]>*, что *[Const_i]* является подстрокой *[Const_j]*, но на сей раз выбрасываем из дизъюнкции литералы вида `(not (str.contains S [Const_i]))` --- они лишние, поскольку `(not (str.contains S [Const_i])) => (not (str.contains S [Const_j]))`. Если после этого остался только один литерал вышеуказанного вида, то дальнейшую оптимизацию применять уже не надо, иначе считаем, что осталось *m>1* литералов `(not (str.contains S [Const'_i]))`. 

Порождаем единственную функцию с двумя предложениями, которая осуществит кодогенерацию для всех этих литералов:
```
No_Multi_[Number] {
    (e.x1 [Const'_1] e.y1) (e.x2 [Const'_2] e.y2) ... (e.xm [Const'_m] e.ym) = False;
    e.Z = True;
}
```
Её вызываем с копированием аргумента *m* раз: `<No_Multi_[Number] (S) (S) ... (S)>`.

**Comment by ylyxa** [comment]
Бóльшая часть кодгена теперь есть, пара вопросов:
1. Что значит "заменить на буквенный идентификатор" в заявке #7? Хотелось бы посмотреть какой-нибудь пример.
2. Что делать, если на входе несколько assert-предложений?

**Comment by TonitaN** [comment]
@ylyxa, например, рассмотрим исходник:
```
(set-logic QF_SLIA)
(set-option :strings-exp true)

(declare-fun x () String)

(assert (str.contains (str.replace_all x "<" "") "<"))

(check-sat)
(get-model)
```
Если тупо порождать функцию кодгеном без экранирования, у неё будет такое имя: `Repl_<_`, и естественно, программа получится некорректной. Поэтому символ `<` заменяем на какой-нибудь буквенный или цифровой код, например, `lt`, и дополнительно добавляем знаки подчёркивания, чтобы было ясно, что это экранирование. Получим имя `Repl__lt_`, которое уже может корректно обрабатываться парсером рефала.

Можно составить таблицу символ (кириллица + служебные символы и пунктуация) - код, где в качестве последнего взять, например, юникод символа (или сгенерировать от балды, поскольку кодген делается для чтения суперкомпиляторами, а не человеком). И потом для представления символа с помощью идентификатора читать его из этой таблицы.

Если на входе несколько `assert`-предложений, это то же самое, что и если они соединены связкой `&`. Так что лучше указать эту связку явно ещё до перехода к КНФ, чтобы могли отработать оптимизации, когда @StepanBog их сделает.

**Comment by Mazdaywik** [comment]
Можно взять в качестве escape-символа знак `_`. Т.е. знак `_` представлять как `__` (точно также, как `\` в Си изображается `\\`), а для других символов можно придумать свою кодировку. Крайний случай — представлять любой символ, недопустимый в идентификаторе как `_xx`, где `xx` — пара шестнадцатеричных цифр (для кодировки ASCII) или `_xxxx`/`_xxxxxxxx` (для Unicode). Но для часто встречающихся символов можно придумать кодировку вроде `>` → `_lt`, `<` → `_gt` и т.д.

**Comment by ylyxa** [comment]
Теперь сразу после парсинга все `assert`-предложения схлопываются в один `and`-блок.

Экранирование реализовано так: любой символ, не являющийся латинской буквой или цифрой, заменяется на `_<код символа>` (ф-ия `ord()`), а сами константы разделяются `__`.

**Comment by TonitaN** [comment]
@ylyxa. спасибо! Закрываю заявку #7 .
По этой заявке осталось ещё экранировать имена переменных. Цитирую [отсюда](https://www.lri.fr/~conchon/TER/2013/2/SMTLIB2.pdf):
> symbol characters: alphanumerics plus any of these punctuation symbols
~ ! @ $ % ^ & * _ - + = < > . ? /

И дальше:

> Symbols are used for attribute values, and sort, variable, logic, theory, constant and
function names. A symbol can be any sequence of symbol characters that does not start with a
digit and is not a reserved word. In addition, user-defined symbols may not begin with an @ or a
period (.); such symbols are reserved for internal use. 

То, что имя функции в smt2-формате записано правильно (т.е. начинается не с цифры, не с собаки и не с точки), нас не интересует --- это пусть проверяет парсер smt-языка. А вот то, что в нём могут встречаться разные другие символы, кроме цифр и английских букв --- потенциальная проблема, т.к. лексер на этом затыкается. Кроме того, потом эти символы нужно будет экранировать при переходе к имени е-переменной (можно --- тем же способом, что вы экранируете константы в именах функций).
Пример:
```
(set-logic QF_SLIA)
(set-option :strings-exp true)
(set-option :produce-models true)

(declare-fun xvvvvvv+112yy () String)

(assert (str.contains xvvvvvv+112yy "A\<BAAA>C"))

(check-sat)
(get-model)
```
